### ISSUE TITLE
RuntimeError錯誤處理

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/gi2_liau7_khoo3#35]
```bash
$ python manage.py makemigrations
Traceback (most recent call last):
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/臺灣言語工具/系統整合/程式腳本.py", line 23, in _走指令
    stdin=stdin, stdout=stdout, stderr=stderr
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'normalize-audio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/fafoy/git/gi2_liau7_khoo3/語料庫/apps.py", line 18, in ready
    程式腳本._走指令(['normalize-audio', 檔名])
  File "/home/fafoy/git/gi2_liau7_khoo3/venv/lib/python3.5/site-packages/臺灣言語工具/系統整合/程式腳本.py", line 32, in _走指令
    .format(指令)
RuntimeError: 檔案無存在，抑是指令參數愛用陣列的形式！！指令：['normalize-audio', '/tmp/tmps3nizu0q/audio.wav']

```

**Comment by sih4sing5hong5** [comment]
#143 順紲做矣
